### ISSUE TITLE
Docker packaging?

### ISSUE THREAD

**Issue by fiskhest** [bressanmarcos/ICS-Timezone-Fixer#3]
I've been bitten with this issue for too long hoping that m$ would fix their mess, so a huge thank you for creating this alternative.

I was intending to selfhost on my own server, but I notice this isn't packaged as a docker container. Any chance you would implement or accept a PR that adds automated docker builds and uploads to docker hub?

**Comment by bressanmarcos** [comment]
> I've been bitten with this issue for too long hoping that m$ would fix their mess, so a huge thank you for creating this alternative.

Same! Happy to help ;D

> I was intending to selfhost on my own server, but I notice this isn't packaged as a docker container. Any chance you would implement or accept a PR that adds automated docker builds and uploads to docker hub?

I feel this is beyond the purpose of this repo. Since all this repo has is a simple PHP script, with no deps, i'd be overkill to manage a whole Docker infra. Keep it simple!
You are free to do that in your own fork, tho!
